[package]
name = "turing-machine"
description = "Library for turing machine construction, simulation."
version = "0.1.0"
authors = ["SunHao-0 <sunhaoyl@outlook.com>"]
edition = "2018"

[dependencies]
rustc-hash = "1.1.0"
pest = "2.1"
pest_derive = "2.1"
thiserror = "1.0"
